plugins: ["quark_plugin_tsp", "quark_plugin_dwave", "quark_plugin_luna"]


luna_problems: &luna_problems [
  "luna_setpacking": { set_size: 13, universe_size: 5, density: 0.4, weights: "equal", seed: 2 },
  # "luna_setpacking": { set_size: 10, universe_size: 5, density: 0.2, weights: "equal", seed: 1 },
  # "luna_hamiltoniancycle": { num_nodes: 6, edge_prob: 0.8, seed: 42 },
  # "luna_hamiltoniancycle": { num_nodes: 10, edge_prob: 0.8, seed: 42 },
  # "luna_minvertexcover": { num_nodes: 5, edge_prob: 0.5, seed: 42 , penalty: 8},
  # "luna_minvertexcover": { num_nodes: 10, edge_prob: 0.5, seed: 42 , penalty: 8},
  # "luna_mis": { num_nodes: 5, edge_prob: 0.4, seed: 42 },
  # "luna_mis": { num_nodes: 10, edge_prob: 0.4, seed: 42 },
  # "luna_maxcut": { num_nodes: 8, edge_prob: 0.5, weight_range: [1, 5], seed: 42 },
  "luna_maxcut": { num_nodes: 14, edge_prob: 0.5, weight_range: [1, 5], seed: 42 },
]

tsp_problems: &tsp_problems [
  "tsp_graph_provider": { nodes: 4, seed: 42 },
  # "tsp_graph_provider": { nodes: 5, seed: 123 }
]


luna_lp_to_qubo: &luna_lp_to_qubo "luna_lp_qubo_mapping"
tsp_to_qubo: &tsp_to_qubo "tsp_qubo_mapping_dnx"

luna_classical_qubo: &luna_classical_qubo [
  "luna_sa": {num_reads: 5},
  # "luna_saga": {},
  # "luna_qbsa": {},
  # "luna_rrsa": {},
  # "luna_pa": {},
  "luna_pt": {},
]

luna_classical_lp: &luna_classical_lp [
  "luna_scip",
  "luna_da",
  "luna_da" : {version: "v4"},
]

# Pipeline definitions

# Luna LP problems -> Luna LP solver (direct)
pipeline_luna_direct: &pipeline_luna_direct [*luna_problems, *luna_classical_lp]

# Luna LP problems -> QUBO mapping -> Luna classical QUBO solvers  
pipeline_luna_via_qubo: &pipeline_luna_via_qubo [*luna_problems, *luna_lp_to_qubo, *luna_classical_qubo]

# TSP problems -> QUBO mapping -> Luna classical QUBO solvers
pipeline_tsp_via_luna: &pipeline_tsp_via_luna [*tsp_problems, *tsp_to_qubo, *luna_classical_qubo]

# TSP problems -> Classical TSP solver (for comparison)
pipeline_tsp_direct: &pipeline_tsp_direct [*tsp_problems, "classical_tsp_solver"]

# TSP problems -> DWave simulated annealer (for comparison)
pipeline_tsp_dwave: &pipeline_tsp_dwave [*tsp_problems, *tsp_to_qubo, "simulated_annealer_dwave": { num_reads: 100 }]

# Luna Problem with DWave
# pipeline_luna_dwave: &pipeline_luna_dwave [*luna_problems, *luna_lp_to_qubo, "simulated_annealer_dwave": { num_reads: 100 }]


pipelines: [
  *pipeline_luna_direct, 
  # *pipeline_luna_via_qubo,
  # *pipeline_tsp_via_luna,
  # *pipeline_tsp_direct,
  # *pipeline_tsp_dwave,
  # pipeline_luna_dwave
]